version: '3.7'

services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - bookstore_bridge

  bookstore:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - bookstore_bridge
networks:
  bookstore_bridge: