version: '2.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - "./mysqldata:var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    networks:
      - bookstore_bridge

  bookstore:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - bookstore_bridge
networks:
  bookstore_bridge: